title: Sizable Stain
email: sizablestaincontact@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Philadelphia's only PoC-run art publication.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sizablestain.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sizablestain

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed